version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nyama
    ports:
      - '3306'


  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
